### PR TITLE
Fix mlnx.pl script for perl include local directory

### PR DESCRIPTION
**Pull request by kcudnik**
For new Perl @INC path must be updated for current directory module
lookup

### CODE REVIEW

**Comment by kcudnik** [comment]
build fail caused by https://github.com/Azure/sonic-swss-common/pull/316 and missing configuration in build docker

**Comment by qiluo-msft** [comment]
What is "new Perl"? and what is the old one?

**Comment by kcudnik** [comment]
5.30 over 5.26

**Comment by kcudnik** [comment]
retest this please

**Pull request merged**
