### PR TITLE
Add support for SAI_SWITCH_ATTR_AVAILABLE_IPMC_ENTRY needed by CRM

### PR DESCRIPTION
**Pull request by PrabhuSreenivasan**
Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>

This change is required for https://github.com/Azure/sonic-swss/pull/1511

### CODE REVIEW

**Comment by PrabhuSreenivasan** [comment]
retest vs  please'

**Comment by PrabhuSreenivasan** [comment]
retest vs please

**Review by kcudnik — APPROVED** [review]
please resolve failed build if related

**Comment by PrabhuSreenivasan** [comment]
retest Azure.sonic-sairedis please

**Comment by PrabhuSreenivasan** [comment]
retest this please

**Comment by PrabhuSreenivasan** [comment]
retest azure-pipelines please

**Comment by PrabhuSreenivasan** [comment]
retest pipelines please

**Comment by PrabhuSreenivasan** [comment]
retest vsimage please

**Comment by PrabhuSreenivasan** [comment]
retest build please

**Comment by PrabhuSreenivasan** [comment]
How can we retest Azure.sonic-sairedis ?

**Comment by PrabhuSreenivasan** [comment]
new vs failures seem unrelated.

**Comment by kcudnik** [comment]
4 failing tests on vs are ok, there is work to fix them, but about azure sonic build was not found, not sure why

**Comment by kcudnik** [comment]
retest Azure.sonic-sairedis please

**Comment by kcudnik** [comment]
retest Azure please

**Comment by kcudnik** [comment]
retest sonic-sairedis please

**Comment by PrabhuSreenivasan** [comment]
> 4 failing tests on vs are ok, there is work to fix them, but about azure sonic build was not found, not sure why

Azure.sonic-sairedis build was done 11 days back and may have got deleted by system. How can we trigger a rebuild?

**Comment by kcudnik** [comment]
retest please

**Comment by kcudnik** [comment]
retest all please

**Comment by kcudnik** [comment]
dont know, you can try force push branch ?

**Comment by kcudnik** [comment]
retest this please

**Comment by PrabhuSreenivasan** [comment]
retest vs please

**Comment by kcudnik** [comment]
``` 
E       RuntimeError: Sonic database config file doesn't exist at /var/run/redis/sonic-db/database_config.json
```

something changed with environment

**Comment by kcudnik** [comment]
@daall Are you aware of any env changes that could lead to this test failures ?

**Comment by daall** [comment]
> @daall Are you aware of any env changes that could lead to this test failures ?

This looks like the issue where the `database_config.json` is not being installed correctly, @qiluo-msft can you please take a look?

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by kcudnik** [comment]
"Retest vs please" solution for all the problems on all PR's XD

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
