### PR TITLE
Use priority attribute matching acl counter using acl entry (#1029)

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by vaibhavhd** [comment]
Not merging this just yet, as tests need to be done separately on 202012 to ensure no new regressions are introduced here.

**Comment by vaibhavhd** [comment]
I tested this on KVM, and although I don't see errors that was previously seen, I see this repeating endlessly after APPLY_VIEW:

`Apr 14 05:03:55.132637 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for DEFAULT_RULE rule
Apr 14 05:03:55.136721 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_1 rule
Apr 14 05:03:55.159411 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_2 rule
Apr 14 05:03:55.175954 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_3 rule
Apr 14 05:03:55.179205 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_4 rule
Apr 14 05:03:55.181211 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_5 rule
Apr 14 05:03:55.183144 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_6 rule
Apr 14 05:03:55.184826 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_9998 rule
Apr 14 05:04:05.130875 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for DEFAULT_RULE rule
Apr 14 05:04:05.131777 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_1 rule
Apr 14 05:04:05.144669 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_2 rule
Apr 14 05:04:05.146071 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_3 rule
Apr 14 05:04:05.153825 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_4 rule
Apr 14 05:04:05.155374 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_5 rule
Apr 14 05:04:05.168642 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_6 rule
Apr 14 05:04:05.173996 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_9998 rule
Apr 14 05:04:15.127291 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for DEFAULT_RULE rule
Apr 14 05:04:15.129384 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_1 rule
Apr 14 05:04:15.129384 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_2 rule
Apr 14 05:04:15.142573 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_3 rule
Apr 14 05:04:15.152305 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_4 rule
Apr 14 05:04:15.153048 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_5 rule
Apr 14 05:04:15.163609 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_6 rule
Apr 14 05:04:15.169455 vlab-01 ERR swss#orchagent: :- getCounters: Failed to get counters for RULE_9998 rule
```

**Comment by kcudnik** [comment]
this is interesting, do you seen any asic operations on after apply view related to acl counter? or any acl? is this error consistent?

**Comment by vaibhavhd** [comment]
> this is interesting, do you seen any asic operations on after apply view related to acl counter? or any acl? is this error consistent?

This error is consistent. There were no ASIC operations during or after APPLY_VIEW.

**Comment by vaibhavhd** [comment]
> > this is interesting, do you seen any asic operations on after apply view related to acl counter? or any acl? is this error consistent?
> 
> This error is consistent. There were no ASIC operations during or after APPLY_VIEW.

The issue is not seen on physical testbed. Tested on an engineering build with deploy-mg + acl config. Fix is good to merge.

**Comment by kcudnik** [comment]
> The issue is not seen on physical testbed. Tested on an engineering build with deploy-mg + acl config. Fix is good to merge.

interesting, so how this is magically fixed? :P

**Pull request merged**
