### PR TITLE
Moved SAI Header to git tag v1.8.1

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
- Moved the SAI header to v1.8.1. 
 ```
    7cd3a7ed84db3fc9cec13496a5339b6fe1888bb7 (HEAD, tag: v1.8.1, origin/v1.8) Update SAI version to V1.8.1 (#1218)
    5913e4cdd0c9c7ae859baa2e18086327b39a94da Fix error when compiling Broadcom SAI with v1.8.0 (#1216)
    5a98bc3c7e86c01f3cf702054f9af7c7c5ca6daf (HEAD, tag: v1.8.0, origin/master, origin/HEAD, master) Update version to 1.8.0 (#1207)
    b3244ceceb45184ffe37da55bb9a98ef126050ce saineighbor.h: Updated SAI_NEIGHBOR_ENTRY_ATTR_ENCAP_INDEX and deprecated SAI_NEIGHBOR_ENTRY_ATTR_ENCAP_IMPOSE_INDEX (#1202)
    8731ca6e09c7ba99b0b009e5821d80598e216756 Add source/dest/double NAPT entry available attributes (#1194)
    f053d899feb9517f2db43ee462589a30572b5ed1 Add switch attributes for hash offset configuration. (#1195)
    13e5cd6940f9a0da1878d00f08e5941e09f16e7f PRBS RX State Data Type (#1179)
    9755845a06525a3c17f03e7b936a70783e8ef068 Packet header based VRF classification (#1185)
    2369ecb59fff1a5cae948d41eea06bf8b71330b2 SAI versioning (#1183)
    744279839c176e68b19734657975e3f5ec6f1a32 Replaced SAI_SWITCH_ATTR_MACSEC_OBJECT_ID with SAI_SWITCH_ATTR_MACSEC_OBJECT_LIST (#1199)
    584c724864fe565357e82d097ddcc7363bddefac [CI] Set up CI&PR with Azure Pipelines (#1200)
    08192237963174cc60edae9b4812a39c43b291fd Add attribute to query available packet DMA pool size (#1198)
    f092ef1e3ce695fc3f9552721025695312b961a2 Add IPv6 flow label hash attribute. (#1192)
    cbc9562bb7a8f2c3a79702b99be55f3b3afa6957 Override VRF (#1186)
    1eb35afdb2146baf40e6c2b8f2f8bfe99075eaee Add SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO format for GB MDIO sysfs access   (#1171)
    b2d4c9a57c7f00b2632c35ca5eb3dd6480f7916a Switch scoped tunnel attributes (#1173)
    96adc95bf8316e1905143d9ecd21f32a43e80d7f Enhancements for MPLS support (#1181)
    3dcf1f2028da4060b345ad78e8a0c87d225bf5d0 Support for ACL extensions in metadata (#1178)
    24076be95b871e8f82ecaeb908cad951dc68896c [meta] Add support for allow empty list tag (#1190)
    a2b3344cdde0bf5a4f8e98e1c676a658c0c615b0 spell check fixes (#1189)
    bf4271bab6e8884bd96050bcba44e3134adaaec3 Do not call sai_metadata_sai get APIs before checking if they are allocated (#1182)
    5d5784dc3dbfc713c92ae7d2c472680b837bb002 [macsec]: Separate XPN configuration attribute from read-only attribute (#1169)
    6d5a9bf5ad17cb82621cabbe2449524320930606 [macsec]: add SAI_MACSEC_ATTR_SUPPORTED_CIPHER_SUITE_LIST (#1172)
    e72c8f3a0cc543cb228554be82c97a63db917740 [meta] Print each tool version in Makefile (#1177)
    8f19677da88c7494d563ef7c5acb0529ecbd0b6e [meta] Add check for START, END and RANBE_BASE enums (#1175)
    24ad7906f145930b2e25682b6248909289d39e72 [meta] Create sai_switch_pointers_t struct (#1174)
    4f5f84df3fcd0e146707df41d3e2837c48f7c760 Tunnel loopback packet action as resource (#1163)
    8a0e82c57aa0e22e696158735516904e7dc14052 [meta] Add create only oid attribute check on switch object (#1170)
    14cf50772e478551920963ecf11f4fd019a0c106 Remove obsolete stub folder (#1168)
    f14f406340e4f5f1b1d674f6fdd5fd861a54c877 [meta] Use safer calloc for integer overflow check (#1166)
```

- Also this PR include changes of this https://github.com/Azure/sonic-sairedis/pull/815
- SAI commit `b2d4c9a57c7f00b2632c35ca5eb3dd6480f7916a Switch scoped tunnel attributes (#1173)` needed change in `sai_redis_switch.cpp` and `sai_vs_switch.cpp` for compilation. 

How I verify:

Verify Build is fine of `libsairedis*.deb, syncd*.deb, swss*.deb`

**### _Please note  build-image  cannot be moved forward with sairedis pointer with this PR/commit since vendor sai packages are still not compiled with SAI1.8.1 Header._**

### CODE REVIEW

**Comment by abdosi** [comment]
@qbdwlr This PR has your commit.

**Review by rlhui — DISMISSED** [review]

**Comment by abdosi** [comment]
Sai redis unit test are failing because of https://github.com/opencomputeproject/SAI/pull/1169 where it seems alias is not maintaining backward compatibility.

**Comment by kcudnik** [comment]
test main::test_macsec_p2p_establishment is failing, since SAI_MACSEC_SA_ATTR_XPN attribute changed from create_and_set to read_only and in that test:
```
BCM56850/test_macsec_p2p_establishment.rec:2021-02-04.14:32:46.658586|c|SAI_OBJECT_TYPE_MACSEC_SA:oid:0x5c000000000636|SAI_MACSEC_SA_ATTR_MACSEC_DIRECTION=SAI_MACSEC_DIRECTION_EGRESS|SAI_MACSEC_SA_ATTR_SC_ID=oid:0x5b000000000631|SAI_MACSEC_SA_ATTR_AN=0|SAI_MACSEC_SA_ATTR_SAK=00000000000000000000000000000000BCF9AD8CE37694552ECF8AB895169604|SAI_MACSEC_SA_ATTR_SALT=000000000000000000000000|SAI_MACSEC_SA_ATTR_MACSEC_SSCI=0|SAI_MACSEC_SA_ATTR_AUTH_KEY=E6BCBC29D9BB2A4E9297A11976D1FFBA|SAI_MACSEC_SA_ATTR_XPN=1
```
is used as SAI_MACSEC_SA_ATTR_XPN=1
at this point test need to be fixed and actual code in VS switch also needs to be fixed, since that attribute is actually used:
```
vslib/src/SwitchStateBaseMACsec.cpp:        SAI_METADATA_GET_ATTR_BY_ID(attr, SAI_MACSEC_SA_ATTR_XPN, attrCount, attrList);
```

Im not mantainer of this code, please ask original author to help here Ze Gan @pterosaur to resolve this issue.

If you want to disable this test case, add also SWSS_LOG_THROW exception in the place where you comment this code in SwitchStateBaseMACsec.cpp

**Review by kcudnik — CHANGES_REQUESTED** [review]
ask Ze Gan to help resolve this or comment code with throw and disable this test case

**Comment by Pterosaur** [comment]
> ask Ze Gan to help resolve this or comment code with throw and disable this test case

Could you temporarily comment this test case? 
Of course, I need some time to fix this issue and submit another PR for it.

**Comment by abdosi** [comment]
> test main::test_macsec_p2p_establishment is failing, since SAI_MACSEC_SA_ATTR_XPN attribute changed from create_and_set to read_only and in that test:
> 
> ```
> BCM56850/test_macsec_p2p_establishment.rec:2021-02-04.14:32:46.658586|c|SAI_OBJECT_TYPE_MACSEC_SA:oid:0x5c000000000636|SAI_MACSEC_SA_ATTR_MACSEC_DIRECTION=SAI_MACSEC_DIRECTION_EGRESS|SAI_MACSEC_SA_ATTR_SC_ID=oid:0x5b000000000631|SAI_MACSEC_SA_ATTR_AN=0|SAI_MACSEC_SA_ATTR_SAK=00000000000000000000000000000000BCF9AD8CE37694552ECF8AB895169604|SAI_MACSEC_SA_ATTR_SALT=000000000000000000000000|SAI_MACSEC_SA_ATTR_MACSEC_SSCI=0|SAI_MACSEC_SA_ATTR_AUTH_KEY=E6BCBC29D9BB2A4E9297A11976D1FFBA|SAI_MACSEC_SA_ATTR_XPN=1
> ```
> 
> is used as SAI_MACSEC_SA_ATTR_XPN=1
> at this point test need to be fixed and actual code in VS switch also needs to be fixed, since that attribute is actually used:
> 
> ```
> vslib/src/SwitchStateBaseMACsec.cpp:        SAI_METADATA_GET_ATTR_BY_ID(attr, SAI_MACSEC_SA_ATTR_XPN, attrCount, attrList);
> ```
> 
> Im not mantainer of this code, please ask original author to help here Ze Gan @Pterosaur to resolve this issue.
> 
> If you want to disable this test case, add also SWSS_LOG_THROW exception in the place where you comment this code in SwitchStateBaseMACsec.cpp

@kcudnik I have asked SAI PR author to make sure change is backward compatible. Will that be correct approach ?

**Comment by kcudnik** [comment]
Any working solution should be fine here, i think this can't be done in one PR, since that XPN attribute changes meaning between v1.7.0 and v1.8.0 sai headers

**Comment by kcudnik** [comment]
another problem with other attribute:
```
  what():  :- sai_deserialize_attr_id: invalid attr id: SAI_MACSEC_SA_ATTR_MINIMUM_XPN
player BCM56850/test_macsec_p2p_establishment.rec: exitcode: 134:
```

you can run tests locally to see if they will pass using "make check"

also aspell needs to be updated:
```
WARNING: Word 'Inseg' is misspelled ../syncd/BestCandidateFinder.cpp
WARNING: Word 'inseg' is misspelled ../syncd/BestCandidateFinder.cpp
WARNING: Word 'insegs' is misspelled ../syncd/BestCandidateFinder.cpp
```

**Comment by kcudnik** [comment]
there is a problem with backward compatible enum attributes, so far we didn't hit that scenario, and currently this is no support for that, fastest way will be to use in that *rec file current value which is not deprecated, and i will add deprecated support to SAI repo later on

**Comment by kcudnik** [comment]
i created SAI metadata update for this scenario https://github.com/opencomputeproject/SAI/pull/1214, but it will also require to update saiserialize.cpp to support new api

**Review by kcudnik — APPROVED** [review]

**Comment by abdosi** [comment]
Need to fix https://github.com/opencomputeproject/SAI/pull/1169 for VS test to pass.

**Comment by kcudnik** [comment]
test error:
```
test_VlanIncrementalConfig failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	
	[<TracebackEntry /home/vsts/work/1/s/sonic-swss/tests/test_vlan.py:125>, <TracebackEntry /home/vsts/work/1/s/sonic-swss/tests/dvslib/dvs_vlan.py:61>]
```

seems not related to XPN, i restarted to see if it will pass

**Comment by kcudnik** [comment]
next PR https://github.com/opencomputeproject/SAI/pull/1215 is bringing SAI_MACSEC_SA_ATTR_XPN back to the place it was at the first place after changing in https://github.com/opencomputeproject/SAI/pull/1169, so code for macsec in sairedis will still need to be revisited (code and tests recordings) to make proper adjustment (@Pterosaur), and if this will be pulled in https://github.com/opencomputeproject/SAI/pull/1214 and updated deserialize_attr_id in saiserialize.cpp then no changes would be required to sairedis.rec in tests with that XPN attributes since all will be supported

**Comment by abdosi** [comment]
This PR and other PR https://github.com/Azure/sonic-sairedis/pull/818  is failing at test_sflow.py . Have re-run multiple times Here are my analysis :- 

Looks like there is some issue with sonic-vs docker used in sonic-sai-redis repo for swss DVS test.
I think Swss debian package used in VS docker is not the same artifact generated by Azure pipeline
I compared md5sum of binaries  of Azure artifact swss debian package and the one running in VS docker and they are not matching. I think the swss Debian running in VS docker is not having this PR  https://github.com/Azure/sonic-swss/pull/1623
And thus test fails.

Tried locally also:
Docker from Artifact ==> Test Fails
Docker from Artifact + Using swss debian from Artifact ==> Test passes.

@lguohan can you please help check this.

cc @kcudnik

**Review by kcudnik — APPROVED** [review]

**Comment by qbdwlr** [comment]
@abdosi: Is there a PR to move the sonic-sairedis pointer forward in sonic-buildimage so that this PR is now included in the official build?

**Comment by abdosi** [comment]
> @abdosi: Is there a PR to move the sonic-sairedis pointer forward in sonic-buildimage so that this PR is now included in the official build?

@qbdwlr : Not yet, as mentioned in PR description we are waiting for Vendor to provide SAI compile with v1.8.1. These should be done soon.

cc @rlhui

**Pull request merged**
