### PR TITLE
[vslib]: Fixbug in cleanup MACsec device

### PR DESCRIPTION
**Pull request by Pterosaur**
The previous regex can only match one device so that the original MACsec devices cannot been cleanup by config reload.

### CODE REVIEW

**Comment by kcudnik** [comment]
please satisfy code coverage

**Comment by Pterosaur** [comment]
> please satisfy code coverage

@kcudnik  Done, please check again.

**Review by kcudnik — APPROVED** [review]

**Comment by yxieca** [comment]
@Pterosaur this change cannot be cherry-picked cleanly. Can you investigate?

**Comment by Pterosaur** [comment]
> @Pterosaur this change cannot be cherry-picked cleanly. Can you investigate?

Please cherry-pick this one: https://github.com/Azure/sonic-sairedis/pull/1007 firstly. I checked it locally.

**Pull request merged**
