### PR TITLE
Advance SAI reference pointer to v1.5.0

### PR DESCRIPTION
**Pull request by wendani**
Signed-off-by: Wenda Ni <wenni@microsoft.com>

### CODE REVIEW

**Comment by lguohan** [comment]
build failure, can you check why?

**Comment by kcudnik** [comment]
seems like some changes happened to SAI and sairedis*cpp needs to be updated as well to adapt the new change, checkout console logs from this failed build

**Comment by wendani** [comment]
retest this please

**Comment by wendani** [comment]
🚀

**Pull request merged**
