### PR TITLE
Add support for syncd first run detection

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by stcheng** [comment]
I use "sai_init_view" and "sai_apply_view" to indicate: creating a new view, and actually applying the view to the ASIC. Which seems to be more readable from my point of view.

**Comment by kcudnik** [comment]
Lets sync with Guohan offline on that

**Comment by stcheng** [comment]
sai_init_view & sai_apply_view :) that's what i propose

**Comment by kcudnik** [comment]
Added in another pull request

**Comment by stcheng** [comment]
ack. regenerate this pull request against the newest master.

**Pull request merged**
