### PR TITLE
[201811] Prevent other notification event storms to keep enqueue unchecked and drained all memory that leads to crashing the switch router

### PR DESCRIPTION
**Pull request by gechiang**
This is to backport the fix made in master branch (https://github.com/Azure/sonic-sairedis/pull/968) to 201811 branch since it could not be cherry picked.

Note: 201811 SYNCD notification queueing implementation is slightly different from 20201230 and above branches so minor changes were made in this PR to accommodate the 20181130 notification queuing code.  this change is exactly the same as that of 201911 (https://github.com/Azure/sonic-sairedis/pull/981) as the queuing code portion is the same between 201911 and 201811.

Copying the same info from above PR that we are back porting to this branch here for clarity of what the issue was about and how we are fixing it:

Recently in one of the production devices we encountered a switch ran out of memory and crashed due to there were too many switch state event such as the following due to many multi bit ECC errors:
```

2021-11-06.18:20:10.251799|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.251845|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252289|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252359|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252406|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252460|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252841|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252917|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252974|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.253020|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.253074|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.253466|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.253519|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.253574|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.253620|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.253674|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.254067|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.254119|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.254197|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.254243|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.254768|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.254871|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.254916|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.254961|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.255112|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.255164|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.255209|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.255254|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.255298|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.255342|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
```
this created a notification storm that eventually all get queued to be serviced by SONiC but SONiC was not able to keep up with the incoming enqueue rate, so it eventually used up all the system memory and crashed...
A previous fix was in place to prevent this if the event was FDB event.  But that one was specifically for FDB events and did not catch this case, so the switch still crashed...

This PR is raised to address this issue by adding additional logic to also prevent other event types to create a storm and overwhelm SONiC.
The enhancement is to save the last event type and keep a count for having consecutively received this same event type.  if a different event type is received, the count will go back to 1 and get counted from there.
If it ever gets into the situation where the switch already exceeded the enqueue threshold (due to the storm) and has over 1000 consecutive notification of this same type, then it will also be dropped regardless of the event type.  
The original FDB event case handling is still kept the same way as before so that as soon as the queue reached its threshold, any new FDB events will be dropped regardless of the consecutive count.

I have tested this on a switch with 201911 code that has this same change in place to ensure that the new logic works fine with FDB events or other events.

### CODE REVIEW

**Comment by gechiang** [comment]
@kcudnik this LGTM build failure:
```
[2021-12-07 17:41:29] [build-stdout] checking for main in -lsai... no
[2021-12-07 17:41:29] [build-stdout] configure: error: libsai is required for syncd
[2021-12-07 17:41:29] [build-stdout] /opt/dist/cpp/tools/configure-wrapper: Configure failed
```
not sure what I need to resolve this... any ideas?  or this is expected, and we can proceed to merge this PR?

**Comment by kcudnik** [comment]
flag "--with-sai=vs" must be specified in configure
https://github.com/Azure/sonic-sairedis/blob/master/lgtm.yml#L30

would you be able to add?

**Comment by gechiang** [comment]
> flag "--with-sai=vs" must be specified in configure https://github.com/Azure/sonic-sairedis/blob/master/lgtm.yml#L30
> 
> would you be able to add?

in 201811 branch I do not see lgtm.yml present.  Do you want me to copy it from let's say 202012 branch to here and commit it as part of this PR?

**Comment by gechiang** [comment]
@kcudnik ewith lgtm.yml added it improved somewhat... next layer is:
```
[2021-12-08 03:50:20] [build-stdout] g++ -DHAVE_CONFIG_H -I. -I..  -g -I../SAI/inc -I../SAI/meta -I../SAI/experimental -ansi -fPIC -std=c++11 -Wall -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Werror -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winline -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros -Wwrite-strings -Wno-switch-default -Wconversion -Wlong-long   -g -O2 -MT tests-tests.o -MD -MP -MF .deps/tests-tests.Tpo -c -o tests-tests.o `test -f 'tests.cpp' || echo './'`tests.cpp
[2021-12-08 03:50:20] [build-stderr] In file included from tests.cpp:1:
[2021-12-08 03:50:20] [build-stderr] sai_meta.h:6:10: fatal error: saimetadata.h: No such file or directory
[2021-12-08 03:50:20] [build-stderr]     6 | #include "saimetadata.h"
[2021-12-08 03:50:20] [build-stderr]       |          ^~~~~~~~~~~~~~~
[2021-12-08 03:50:20] [build-stderr] compilation terminated.
[2021-12-08 03:50:21] [build-stdout] make[2]: Leaving directory '/opt/src/meta'
[2021-12-08 03:50:21] [build-stderr] make[2]: *** [Makefile:875: tests-tests.o] Error 1
[2021-12-08 03:50:21] [build-stderr] make[1]: *** [Makefile:407: all-recursive] Error 1
[2021-12-08 03:50:21] [build-stdout] make[1]: Leaving directory '/opt/src'
[2021-12-08 03:50:21] [build-stderr] make: *** [Makefile:339: all] Error 2
[2021-12-08 03:50:21] [build-stderr] + '[' -f build.ninja ']'
[2021-12-08 03:50:21] [build-stderr] + '[' -d ../_lgtm_build_dir ']'
```
Any advice what I need to add/change to overcome this one?
Thanks!

**Comment by kcudnik** [comment]
seems like "make" is not executed in SAI/meta directory and saimetadata.h is not build, but not sure why this happens :/

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
