### PR TITLE
[SAI] upgrade to SAI header version v1.3.3

### PR DESCRIPTION
**Pull request by yxieca**
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by arkadiyshapiro** [comment]
Does this imply a change of SAI version compatible with next SONiC release (Sept)?

**Comment by yxieca** [comment]
@arkadiyshapiro 

Thanks for the question. This is the first change. I'll have to upgrade SAI version soon to make it a combo deal. The change will be enabled in master branch with that change to come.

**Comment by arkadiyshapiro** [comment]
K it will be good to see a collective list of changes for this new SAI version.

**Comment by arkadiyshapiro** [comment]
OK if there is minor version bump, would be good to see complete list of changes so silicon vendors know what needs to be implemented.

**Comment by qiluo-msft** [comment]
Please use 'squash merge' if you can.

**Pull request merged**
