### PR TITLE
[SAI]: Support for bmtor api

### PR DESCRIPTION
**Pull request by marian-pritsak**
Update SAI pointer to master
Add new extension api bmtor

Signed-off-by: Marian Pritsak <marianp@mellanox.com>

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
@marian-pritsak , can you check why build fails?

**Comment by kcudnik** [comment]
missing implementation for bmtor of api struct, take a example like sai_vs_hash.cpp

**Comment by marian-pritsak** [comment]
Pending https://github.com/opencomputeproject/SAI/pull/902

**Pull request closed without merging**
