### PR TITLE
Add check ASIC vs DB state after comparison logic

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by lguohan** [comment]
@kcudnik , can you take a look?

**Comment by kcudnik** [comment]
yea, i send email about this, it's jenkins issue
`+ sudo service rsyslog start
rsyslog: unrecognized service
Build step 'Execute shell' marked build as failure
Archiving artifacts`

**Comment by kcudnik** [comment]
test this please

**Comment by yxieca** [comment]
Looks like your DB/SAI comparison is working! The only problem is that it surely triggers Broadcom SAI segment fault while comparing.

Can you make it optional?

I think the best way to trigger it might be reuse the syncd_request_shutdown program to send an event to check. What do you think?

Alternative would be if you receive a signal then start checking. like USR1 :-)

**Comment by kcudnik** [comment]
i would rather like to avoid using linux signals to make make something like this

**Pull request merged**
