### PR TITLE
[syncd] Comparison logic add support to LABEL attribute with higher priority

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by lguohan** [comment]
do you support the comparison logic between without label to having the label?

**Comment by kcudnik** [comment]
yes, this is supported, but since there is no label to match in current view, matching will be based on lag_member and port or if lag is empty then match by number for same attributes

**Comment by lguohan** [comment]
can you addd unit test for this pr, then we should be good.

**Comment by kcudnik** [comment]
i added test case where we don't have label, and then we do, for 2 lags, 2 operations are expected to SET label from new viw

**Review by lguohan — APPROVED** [review]

**Pull request merged**
