### PR TITLE
sonic-sairedis changes for MPLS support

### PR DESCRIPTION
**Pull request by qbdwlr**
Refer to HLD:  https://github.com/Azure/SONiC/pull/706
Changes depend on SAI v1.8.0

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]
very good job with that PR

**Comment by lguohan** [comment]
why build failure?

**Comment by qbdwlr** [comment]
> why build failure?

As stated in the initial comment, these changes depend on SAI v1.8.0 which is not the current version of SAI used by sonic-sairedis master.

**Comment by abdosi** [comment]
@qbdwlr can you giver permission to you fork repo for me to checkout code ?  currently there is deadlock . To move SAI 1.8 Header i need this change to avoid compilation error.

**Comment by qbdwlr** [comment]
> @qbdwlr can you giver permission to you fork repo for me to checkout code ? currently there is deadlock . To move SAI 1.8 Header i need this change to avoid compilation error.
> 
> never mind I am able to fork it and merge this branch locally.

@abdosi OK.  Please let me know if there is anything else you need from me for this effort.

**Comment by abdosi** [comment]
> > @qbdwlr can you giver permission to you fork repo for me to checkout code ? currently there is deadlock . To move SAI 1.8 Header i need this change to avoid compilation error.
> > never mind I am able to fork it and merge this branch locally.
> 
> @abdosi OK. Please let me know if there is anything else you need from me for this effort.

@qbdwlr This changes have got merged now  via https://github.com/Azure/sonic-sairedis/pull/816. Please close this PR accordingly.

**Comment by qbdwlr** [comment]
Changes are included in full with https://github.com/Azure/sonic-sairedis/pull/816.
This PR is no longer required.

**Pull request closed without merging**
