### PR TITLE
Add basic param validation for several SAI objects

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by lguohan** [comment]
are these validations also applied to virtual switch?

**Comment by stcheng** [comment]
this validations happen on sairedis layer.

**Comment by kcudnik** [comment]
Not direclty, but via syncd, but i also though how to make those apply on each sai, but i coudnt found right solution yet, expect a separate intermidiate library, lets meet today, i have few question about tunell

**Comment by kcudnik** [comment]
Merged this change to metadata branch

**Pull request closed without merging**
