### PR TITLE
[cbf] Add Class Based Forwarding support

### PR DESCRIPTION
**Pull request by abanu-ms**
* Added support for MAP_LIST serialization and deserialization

* Add FC to QoS maps

* Added a UT to validate the changes

* Add NHG map API implementation

* Add VS object availability for NHG maps

Signed-off-by: Alexandru Banu <v-albanu@microsoft.com>

### CODE REVIEW

**Review by kcudnik — DISMISSED** [review]

**Comment by kcudnik** [comment]
please fix build process and resolve conflicts

**Comment by abanu-ms** [comment]
In order to fix  the build we need a newer version of SAI. We're going to wait for the official SAI module update before merging this in.

**Comment by TACappleman** [comment]
@kcudnik could you review this change, now that the SAI dependency issue is solved?

**Review by kcudnik — APPROVED** [review]

**Comment by TACappleman** [comment]
@kcudnik Thanks - can this also be merged? (We don't have permissions!)

**Pull request merged**
