### PR TITLE
[syncd] Disable use bulk api by default

### PR DESCRIPTION
**Pull request by kcudnik**
currently disabled since most vendors don't support that yet

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by daall** [comment]
retest vs please

**Comment by lguohan** [comment]
retest vs please

**Comment by kcudnik** [comment]
retest vs please

**Comment by lguohan** [comment]
retest this please

**Comment by kcudnik** [comment]
retest vs please

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
