### PR TITLE
Fix branch reference error

### PR DESCRIPTION
**Pull request by xumia**
Fix branch reference error, change master to 202012

### CODE REVIEW

**Comment by kcudnik** [comment]
build failing because of this change ?

**Comment by xumia** [comment]
@kcudnik , Failed to build on 202012 branch, I am not sure whether the change is correct or not.
https://dev.azure.com/mssonic/build/_build/results?buildId=17872&view=results

**Comment by kcudnik** [comment]
https://dev.azure.com/mssonic/build/_build/results?buildId=17872&view=logs&j=05061332-bfdb-5f6d-a09c-bb63eec6669c&t=9e60e50c-b4b6-53d2-7fd2-99b13f45e3ec
```
macsecorch.cpp: In member function 'bool MACsecOrch::createMACsecSA(sai_object_id_t&, sai_object_id_t, sai_macsec_direction_t, sai_object_id_t, macsec_an_t, uint8_t*, uint8_t*, sai_uint32_t, uint8_t*, sai_uint64_t)':
macsecorch.cpp:1851:19: error: 'SAI_MACSEC_SA_ATTR_CONFIGURED_EGRESS_XPN' was not declared in this scope
         attr.id = SAI_MACSEC_SA_ATTR_CONFIGURED_EGRESS_XPN;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
macsecorch.cpp:1851:19: note: suggested alternative: 'SAI_MACSEC_SA_ATTR_MINIMUM_XPN'
         attr.id = SAI_MACSEC_SA_ATTR_CONFIGURED_EGRESS_XPN;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   SAI_MACSEC_SA_ATTR_MINIMUM_XPN
macsecorch.cpp:1857:19: error: 'SAI_MACSEC_SA_ATTR_MINIMUM_INGRESS_XPN' was not declared in this scope
         attr.id = SAI_MACSEC_SA_ATTR_MINIMUM_INGRESS_XPN;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
macsecorch.cpp:1857:19: note: suggested alternative: 'SAI_MACSEC_SA_ATTR_MINIMUM_XPN'
         attr.id = SAI_MACSEC_SA_ATTR_MINIMUM_INGRESS_XPN;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   SAI_MACSEC_SA_ATTR_MINIMUM_XPN
```

this changed on master at some point, and those names are no longer valid, could you sync that with master?

**Review by qiluo-msft — APPROVED** [review]

**Comment by kcudnik** [comment]
@xumia When merging - please use SQUASH since it's causing merges in branch:
```
| *   783c82b (origin/202012) Merge pull request #834 from xumia/fix-azp-202012
| |\
| | * c28318f Fix sonic-swss branch reference issue
| | * 08718ef Fix branch reference error
| |/
| * bb13d59 Update call git clean on debian/rules (#826)
```

**Comment by kcudnik** [comment]
please fix this by squashing them and making force push on 202012

**Comment by xumia** [comment]
@kcudnik, what is the impact? Is there any unexpected change in 202012 branch? Could you please add some commands for me to run?

**Comment by kcudnik** [comment]
it's just for esthetic purpose, ok, skip this one, just remember next time click checkbox "squash and merge" on github

**Pull request merged**
