### PR TITLE
[SAI] Update Submodule with Fixes

### PR DESCRIPTION
**Pull request by alexrallen**
Update SAI submodule v1.9 with the following fixes

```
7594e53 (HEAD, origin/v1.9) Skip brcm teardown assertion (#1423) (#1428)
0c33f4a [FIX]Fix the circular reference issue when build sai header py (#1427)
7e0fc24 Add support for building under Doxygen 1.9.1 (#1414) (#1424)
8ecf3ef [Fix]Correct enum check on branch 1.9 (#1418)
e2b2f39 Add Thrift 0.14.1 compatibility (#1403) (#1416)
```

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Review by kcudnik — APPROVED** [review]

**Comment by kcudnik** [comment]
@alexrallen can you also make port for branch 202012 ?

**Comment by prsunny** [comment]
> @alexrallen can you also make port for branch 202012 ? SAI branch v1.9 already contains merged fix

@kcudnik - isn't it this one - https://github.com/Azure/sonic-sairedis/pull/1012 ?

**Comment by kcudnik** [comment]
ah yes ! thanks Prince !

**Comment by dgsudharsan** [comment]
@kcudnik  @prsunny Can we merge this?

**Pull request merged**
