### PR TITLE
sairedis: add while loop to make syncd processEvent() handle as many entries as possible in one event call

### PR DESCRIPTION
**Pull request by dzhangalibaba**
…ction

* add while() loop to handle entries when buffer is Not empty

  Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by dzhangalibaba** [comment]
could we make some progress on this, it is pending for a long time. Thanks

**Comment by kcudnik** [comment]
@dzhangalibaba its waiting for my review, and i was on vacation, im back now :)

**Comment by dzhangalibaba** [comment]
@kcudnik This is part of routing performance optimization. We want to handle as many events as possible already in the consumer buffer in one process function instead of waiting the while loop for each event. This was discussed about one month ago in the 4 way meeting. In this way, the performance improved ~200-300 routes per second.

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by dzhangalibaba** [comment]
@qiluo-msft   is this PR OK to be merged now? Who can Help? Thanks

**Pull request merged**
