### PR TITLE
[FlexCounter] Add trap flow counter support

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**What I did**

Add trap flow counter support. See HLD: https://github.com/Azure/SONiC/pull/858

**Why I did it**

Flow counters are usually used for debugging, troubleshooting and performance enhancement processes. Host interface trap counter can get number of received traps per Trap ID.

**How I verified it**

Manual test/VS test/sonic mgmt test

**Details if related**

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by kcudnik** [comment]
can  you try to add empty commit just to trigger build, i restarted it from github, but no clue why it's timing out

**Comment by kcudnik** [comment]
you need to have diff code coverage passed:
Coverage: 0%
Threshold: 50%

**Comment by Junchao-Mellanox** [comment]
Hi @kcudnik , I don't see any unit test for FlexCounter, could you tell where can I find the test case?

**Comment by kcudnik** [comment]
you would need to start create them, not all components have started to have unittests yet, you could follow schema in unittests/meta in unittests/syncd directory

**Comment by kcudnik** [comment]
please resolve conflicts after merging ACL counters

**Comment by Junchao-Mellanox** [comment]
Hi @kcudnik , the failure "Cancelled after 180m" is not caused by my change. I see that the step "Install dependencies" takes almost 3hrs.

**Comment by kcudnik** [comment]
why you need mockable interface at all? and not use "-fno-access-control" to have access to private methods

**Comment by Junchao-Mellanox** [comment]
> why you need mockable interface at all? and not use "-fno-access-control" to have access to private methods and also please dont put code in header files

Hi @kcudnik , 

1. Why we need mockable interface? I don't understand here. Say we have SaiInterface::func, we want to mock it in test case A and test case B, and we want it behave differently in A and B. How can we achieve this without mockable interface?
2. I will move the code from header to cpp file.

**Comment by kcudnik** [comment]
in my understanding Mock class should be only wrapper to expose methods/variables for which we don't have have access since they are ether protected or private, and testing them directly would be much simpler. Behavior should be the same since mock should be created for specific class ?, it could be for base interface also i guess

**Comment by Junchao-Mellanox** [comment]
Maybe "-fno-access-control" can do the job. But MockableInterface provide following capability:
1. Mock any SaiInterface members in any test case with different implementation. E.g. the function getStatExt can fill different counter value if need.
2. It is easy to mock negative case. E.g, the function create can return SAI_INVALID_PARAMTER if need.
3. The implementation of the mocked function can be change dynamically without affecting any other test case.

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
