### PR TITLE
[MultiDB] use new multiDB API/cmd in new added codes

### PR DESCRIPTION
**Pull request by dzhangalibaba**
* correct multiDB API/cmd in new added codes

Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by dzhangalibaba** [comment]
retest LGTM

**Comment by dzhangalibaba** [comment]
retest please

**Comment by dzhangalibaba** [comment]
retest this please

**Comment by dzhangalibaba** [comment]
@qiluo-msft  what's this LGTM analysis failure means . 
Merge pull request #608 from smaheshm/master is not passed checking but merged ?

**Comment by daall** [comment]
retest this please

**Pull request merged**
