### PR TITLE
Revert "[py] Add sairedis python module skeleton"

### PR DESCRIPTION
**Pull request by daall**
Reverts Azure/sonic-sairedis#607

### CODE REVIEW

**Comment by daall** [comment]
retest vs please

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
The LGTM merge build is working, but the checker is failing because it can't build master. I think this is OK. Still looking into the vs failures.

**Comment by daall** [comment]
It's not clear to my why the revert is breaking the sai player tests. @kcudnik I don't know whether it's easier to fix this or fix the build issue from the original PR, just give me a heads up when you're able to take a look at this and we can figure out what to do next.

**Comment by kcudnik** [comment]
i would like to fix master, not sure why its failing on that include, since that include file is present in swss-common

**Comment by lguohan** [comment]
the problem is that python directory is not using Makefile.am, so that configure.ac is not generate the correct Makefile.

**Comment by lguohan** [comment]
fixed in #615 

https://lgtm.com/logs/6fbd60b61c86ef989bf1a7034fb3b378773f38f7/lang:cpp

@kcudnik, let's make sure we merge the pr that has pass the lgtm test. it is a little bit difficult to fix it later.

**Pull request closed without merging**
