### PR TITLE
Enable SAI_SWITCH_ATTR_UNINIT_DATA_PLANE_ON_REMOVAL attribute

### PR DESCRIPTION
**Pull request by tbgowda**
Enable SAI_SWITCH_ATTR_UNINIT_DATA_PLANE_ON_REMOVAL attribute for all platforms based on capability

- Remove Mellanox specific checks
- Check whether the attribute is supported
- Call SAI API if it is supported, else ignore

Test Done:

Tested with corresponding support in SAI to check if attribute is being set correctly.

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by tbgowda** [comment]
Hello, can this be merged? It looks like there is a baseline failure with the vstest unrelated to these changes?

**Comment by tbgowda** [comment]
Hi @yxieca , The failing tests seem to be baseline. I see that other PRs are also failing the same tests. Please let me know if it is fixed, I will sync to the latest refpoint and re-trigger the run. On the other hand, if it is indeed a known issue, could you please help merge this PR?

**Review by yxieca — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Pull request merged**
