### PR TITLE
[vslib]: Add MACsec xpn support

### PR DESCRIPTION
**Pull request by Pterosaur**
This PR should wait for https://github.com/Azure/sonic-buildimage/pull/8702

Signed-off-by: Ze Gan <ganze718@gmail.com>

### CODE REVIEW

**Comment by kcudnik** [comment]
Please also add unittests to cover this functionality

**Comment by Pterosaur** [comment]
> Please also add unittests to cover this functionality

I didn't find an existing unittest file for MACsecManager and SwitchStateBase, should I write a new one to cover all functions for these two classes I changed?

**Comment by kcudnik** [comment]
yea, you can create those stests, and add your part only. as for all related macsec related files, i would like you to start working on unittest for them, i already added couple of them in unittests/vslib/, and for future code you are adding you should also add unittests together

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
