### PR TITLE
Add warm boot support for virtual switch

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by lguohan** [comment]
you need to create the linux host interface upon warm boot if it has been created before.

**Comment by kcudnik** [comment]
scenario with working host interfaces is not supported yet, this is first PR of warm boot support, currently only pure virtual warm boot is supported, if necessary i can add linux hostif support in the future

**Comment by kcudnik** [comment]
test this please

**Comment by kcudnik** [comment]
Agree, but this also requires to dump more stuff from hostif and vs local fdb table, i will think how to do that. There may be some challenges here, since currently we have tap devices and fd descriptors opened, and they will change during system boot. But it's definitely doable.

**Pull request merged**
