### PR TITLE
ARM32 bit fixes, for 64bit printf format specifier

### PR DESCRIPTION
**Pull request by antony-rheneus**
Signed-off-by: Antony Rheneus <arheneus@marvell.com>

### CODE REVIEW

**Comment by kcudnik** [comment]
why arm is not accepting standard prefixes ? this actually makes code much more messy :/

**Comment by jleveque** [comment]
@kcudnik: The "PRI..." constants which get defined differently depending on the architecture you're compiling for, thus making the code more portable. Some archs define a 64-bit int as a `long`, some as a `long long`. Withe this change, we never have to worry about the underlying type.

**Comment by kcudnik** [comment]
yea grepped via headers, more portable less readability  XD

**Comment by jleveque** [comment]
Yes, unfortunately we sacrifice readability for portability.

**Pull request merged**
