### PR TITLE
[SAI] Update SAI submodule to v1.5.1

### PR DESCRIPTION
**Pull request by daall**
* Defining new serdes attributes (#1002)
* Improve debug counter enums (#1006)
* Introduce buffer pool type SAI_BUFFER_POOL_TYPE_BOTH (#986)

Signed-off-by: Danny Allen <daall@microsoft.com>

### CODE REVIEW

**Comment by kcudnik** [comment]
@lguohan  something wrong with jenkins ? cant build

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
fixed a build dependency https://github.com/Azure/sonic-build-tools/commit/2355866e7da4c6be64379ba31046d2ce7f0dc813

**Comment by lguohan** [comment]
@daall , looks like there are missing implementation needed.

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
@lguohan added!

**Pull request merged**
