### PR TITLE
Remove SAI_SWITCH_ATTR_CUSTOM_RANGE_START in player

### PR DESCRIPTION
**Pull request by stcheng**

### CODE REVIEW

**Comment by kcudnik** [comment]
why you want to remoev it ?

**Comment by stcheng** [comment]
1. this attribute is deprecated and no longer in use and not fully supported across different platforms
2. the default is false so no need to add it here.

**Comment by kcudnik** [comment]
this attribute is internal usage only by sairedis

**Comment by stcheng** [comment]
updated to use RANGE_BASE instead of using RANGE_START

**Pull request merged**
