### PR TITLE
Extend response timeout from 60s to 120s

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Extend response timeout from 60s to 120s for Mellanox spectrum 3.

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox  before we merge it i would like to understand first if this is correct for all other ASICs and not just for SPC3.

**Comment by Junchao-Mellanox** [comment]
Hi @liat-grozovik , this change will apply to all ASIC, not only for SPC3.

**Comment by kcudnik** [comment]
this is response for redis database on GET api, why its increased ??

**Comment by Junchao-Mellanox** [comment]
Hi @kcudnik, now in spectrum 3 platform, firmware start slower than spectrum 2 and it may take more than 60 seconds for the "sending syncd INIT view" and wait for notify response. So I extend the response time for Mellanox spectrum 3 platform, and it only affect the startup time. There is also an internal firmware version which already improve the time usage, and we can change the response time back to 60 seconds once that firmware version release and upstream.

**Comment by kcudnik** [comment]
Is device at this point configured ? what about warm boot ?

**Comment by lguohan** [comment]
i suggest to add an command line option so that we can customize for different asic.

**Comment by kcudnik** [comment]
@Junchao-Mellanox if you want to do it please add this as custom parameter in sairedis similar fashion  as SAI_REDIS_SWITCH_ATTR_CONTEXT

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox if you want to do it please add this as custom parameter in sairedis similar fashion as SAI_REDIS_SWITCH_ATTR_CONTEXT

I will close this PR first and discuss with Liat and Kebo about this issue. Thanks for your suggestion.

**Pull request closed without merging**
