### PR TITLE
Add virtual switch unittests channel via redis

### PR DESCRIPTION
**Pull request by kcudnik**
For easier testing when using python framework

### CODE REVIEW

**Comment by kcudnik** [comment]
test this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by kcudnik** [comment]
Thanks for fixing jenkins

**Pull request merged**
