### PR TITLE
[syncd_saiswitch]: Keep full port oids

### PR DESCRIPTION
**Pull request by marian-pritsak**
Keep port oids in COUNTERS_DB in serializable format
This way client code can reuse sai_deserialize... api

### CODE REVIEW

**Comment by stcheng** [comment]
could you explain a little bit more about this change? what client code is to reuse the `sai_deserialize_` api? any examples?

**Comment by stcheng** [comment]
could you provide an output of the database dump?

**Comment by marian-pritsak** [comment]
In case of PFC WD we run an arbitrary .lua plugin on Counters DB to check if storm condition is met. According to design, it is going to receive notification from .lua script indicating that queue state changed.
It would be better to have oids in serializable format in order for watchdog to just deserialize them without modification.

**Comment by stcheng** [comment]
what will be the final output in the database?

**Comment by marian-pritsak** [comment]
``` 
1) "COUNTERS:oid:0x100000000023a"
 2) "COUNTERS:oid:0x100000000012a"
 3) "COUNTERS:oid:0x100000000038e"
 4) "COUNTERS:oid:0x100000000036c"
 5) "COUNTERS:oid:0x1000000000190"
 6) "COUNTERS:oid:0x100000000049e"
 7) "COUNTERS:oid:0x1000000000548"
 8) "COUNTERS:oid:0x100000000025c"
 9) "COUNTERS:oid:0x1000000000416"
10) "COUNTERS:oid:0x1000000000306"
11) "COUNTERS:oid:0x10000000002e4"
...
```

**Comment by marian-pritsak** [comment]
```
127.0.0.1:6379[2]> hgetall COUNTERS_PORT_NAME_MAP
 1) "Ethernet0"
 2) "oid:0x1000000000526"
 3) "Ethernet100"
 4) "oid:0x100000000025c"
 5) "Ethernet104"
 6) "oid:0x100000000027e"
 7) "Ethernet108"
 8) "oid:0x10000000002a0"
 9) "Ethernet112"
10) "oid:0x10000000002c2"
11) "Ethernet116"
12) "oid:0x10000000002e4"
13) "Ethernet12"
14) "oid:0x1000000000504"
...
```

**Comment by kcudnik** [comment]
im ok with this change but just remember to update related components to be aware of this change

**Comment by stcheng** [comment]
this commit along with the commit in the swss repository are breaking the image.

**Comment by stcheng** [comment]
this change goes along with this: https://github.com/Azure/sonic-swss/pull/331

**Pull request merged**
