### PR TITLE
Check sairedis submodule SAI headers against vendor SAI headers

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by lguohan** [comment]
can this be part of build instead of test?

**Comment by kcudnik** [comment]
yes, but why you want this as a build part ?

**Comment by lguohan** [comment]
in some build cases we bypass the test. it is better to integrate with
autoconfigure.

**Comment by kcudnik** [comment]
ok, will update

**Comment by kcudnik** [comment]
retest this please

**Comment by kcudnik** [comment]
retiring

**Pull request closed without merging**
