### PR TITLE
acquire lock before accessing shared redis context

### PR DESCRIPTION
**Pull request by anilkpandey**
Multiple threads in syncd access ASIC_DB through the same redis context. g_mutex is used to synchronize the access as hiredis is not thread safe.
Function try_translate_vid_to_rid(), which accesses ASIC_DB was being called unprotected. This caused  one of the threads to stuck on redisBufferRead().

(gdb) bt
#0 0x00007f15301cd22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
#1 0x00007f1537ebf6a2 in read (__nbytes=16384, __buf=0x7f152d6b0910, 
__fd=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#2 redisBufferRead (c=0x55c450ffdde0) at hiredis.c:802
#3 0x00007f1537ebf9a0 in redisGetReply (c=0x55c450ffdde0, 
reply=reply@entry=0x7f152d6b4a00) at hiredis.c:888
#4 0x00007f1537c612d0 in swss::RedisReply::RedisReply (this=0x7f152d6b4a00, 
db=0x55c451001e80, command=...) at redisreply.cpp:33
#5 0x00007f1537c614c2 in swss::RedisReply::RedisReply (this=0x7f152d6b4a00, 
db=<optimized out>, command=..., expectedType=3) at redisreply.cpp:45
#6 0x00007f1537c7efba in swss::RedisClient::hset (this=0x55c450ffd510, 
key="ASIC_STATE:SAI_OBJECT_TYPE_FDB_ENTRY:{\"bvid\":\"oid:0x26000000000e17\",\"mac\":\"3C:2C:99:8B:35:BC\",\"switch_id\":\"oid:0x21", '0' <repeats 12 times>, "\"}", field="SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID", 
value="oid:0x3a00000000104d") at redisclient.cpp:56

### CODE REVIEW

**Comment by lguohan** [comment]
@anilkpandey, can you resolve the conflict?

**Comment by anilkpandey** [comment]
> @anilkpandey, can you resolve the conflict?

I am not able to, may be because I don't have write access.

**Comment by prsunny** [comment]
You can merge/rebase from master and push to this PR. You don't have to use the resolve button above.

**Comment by prsunny** [comment]
Looks like the editor added a lot of tab spaces. Kindly revert the space changes and recommit.

**Comment by anilkpandey** [comment]
> Looks like the editor added a lot of tab spaces. Kindly revert the space changes and recommit.

Done

**Pull request merged**
