### PR TITLE
[submodule]: Advance SAI to v1.8

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

#### Why I did it
* To pick up missing `zmq` dependency
* To fix https://github.com/Azure/sonic-buildimage/issues/7403

#### How I did it
* Advanced `SAI` submodule

#### How to verify it
1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin

#### Description for the changelog

```
Commits on Jul 07, 2021
[meta] Skip objects on (de)serialize acl field data mask (#1273) (#1275) 5254200

Commits on Aug 27, 2021
[tests] Add missing lib -lzmq to saithrift (#1299) a6af2e8 
```

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Comment by nazariig** [comment]
@kcudnik please have a look

**Review by kcudnik — APPROVED** [review]

**Comment by nazariig** [comment]
@volodymyrsamotiy / @liat-grozovik FYI

**Comment by kcudnik** [comment]
test_recirc_port failure not related to this PR

**Comment by liat-grozovik** [comment]
@nazariig do we need the same for 292106?

**Comment by nazariig** [comment]
> 
> 
> @nazariig do we need the same for 202106?

@liat-grozovik looks so, but need to double check From what can i see in the code, is that `202106` sairedis also doesn't have `zmq` dependency

**Pull request merged**
