### PR TITLE
[SAI]: update sai header

### PR DESCRIPTION
**Pull request by sihuihan88**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by lguohan** [comment]
build fails, is that expected?

**Comment by sihuihan88** [comment]
retest please

**Comment by lguohan** [comment]
retest this please

**Comment by sihuihan88** [comment]
retest this please

**Comment by sihuihan88** [comment]
retest this please

**Comment by sihuihan88** [comment]
retest this please

**Comment by sihuihan88** [comment]
retest this please

**Pull request merged**
